In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.mixture import GaussianMixture
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


import tensorflow as tf
from keras.models import Sequential,load_model
from keras import layers,Input
from keras.losses import binary_crossentropy
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
from keras.callbacks import ModelCheckpoint
from keras.regularizers import L1L2
import keras.backend as K

2023-10-13 18:07:33.248363: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-13 18:07:35.034324: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


2023-10-13 13:44:26.249848: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [30]:
arry=np.array([[[1,11],[2,12],[3,13],[4,14],[5,15],[6,16],[7,17],[8,18],[9,19],[10,20]],[[1,11],[2,12],[3,13],[4,14],[5,15],[6,16],[7,17],[8,18],[9,19],[10,20]]])
# arry=np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]]])
print(arry.shape)
print(arry)
print(arry.reshape((2,5,4)))

(2, 10, 2)
[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]

 [[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]
[[[ 1 11  2 12]
  [ 3 13  4 14]
  [ 5 15  6 16]
  [ 7 17  8 18]
  [ 9 19 10 20]]

 [[ 1 11  2 12]
  [ 3 13  4 14]
  [ 5 15  6 16]
  [ 7 17  8 18]
  [ 9 19 10 20]]]
[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]

 [[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


In [2]:
state0=np.load('../Data/new/2gsps/state0.npy')
state1=np.load('../Data/new/2gsps/state1.npy')
output0=np.zeros((state0.shape[0]))
output1=np.ones((state1.shape[0]))
print(state0.shape)

(6000, 8192, 2)


In [3]:
x=np.vstack((state0,state1))
print(x.shape)
y=np.hstack((output0,output1))
print(y.shape)

(12000, 8192, 2)
(12000,)


In [8]:

st,ed=700,3700
x_train, x_test, y_train, y_test = train_test_split(x[:,st:ed,:], y, test_size=0.30, random_state=45)
print(x_train.shape)
print(y_train.sum())

x_train=np.mean(x_train,axis=1)
x_test=np.mean(x_test,axis=1)

# x_train=x_train.reshape((x_train.shape[0],x_train.shape[1]*2))
# x_test=x_test.reshape((x_test.shape[0],x_test.shape[1]*2))
print(x_train.shape)

(8400, 3000, 2)
4233.0
(8400, 2)


## Logistic Regression

In [9]:
# x_trainC=x_train.reshape((x_train.shape[0],x_train.shape[1]*2))
# x_testC=x_test.reshape((x_test.shape[0],x_test.shape[1]*2))
classifier = LogisticRegression(random_state = 42, max_iter=500)
classifier.fit(x_train, y_train)
print(classifier.score(x_test,y_test))
pred = classifier.predict(x_test)

0.9666666666666667


## SVM

In [10]:
model=SVC(decision_function_shape='ovo')
model.fit(x_train,y_train)
print(model.score(x_test,y_test))

0.9661111111111111


## GMM

In [11]:
Y=list(zip(np.append(np.mean(state0[:,st:ed,0],axis=1),np.mean(state1[:,st:ed,0],axis=1)),np.append(np.mean(state0[:,st:ed,1],axis=1),np.mean(state1[:,st:ed,1],axis=1))))
gmm_Y=GaussianMixture(n_components=2,covariance_type='full').fit(Y)
bitstring=np.split(gmm_Y.predict(Y),2)
print('P(0|0)=',len(bitstring[0][bitstring[0]==0])/len(bitstring[0]))
print('P(1|1)=',len(bitstring[1][bitstring[1]==1])/len(bitstring[1]))
X=list(zip(np.mean(state0[:,st:ed,0],axis=1),np.mean(state0[:,st:ed,1],axis=1)))
gmm_Y_1=GaussianMixture(n_components=1,covariance_type='spherical').fit(X)
X=list(zip(np.mean(state1[:,st:ed,0],axis=1),np.mean(state1[:,st:ed,1],axis=1)))
gmm_Y_2=GaussianMixture(n_components=1,covariance_type='spherical').fit(X)

P(0|0)= 0.9658333333333333
P(1|1)= 0.9601666666666666


## NN

In [17]:
def arch():
    model=Sequential()
    model.add(Input(shape=(2)))
    model.add(Dense(32,activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(16,activation='relu'))
    model.add(Dropout(0.5))
    # model.add(Dense(16,activation='relu'))
    # # model.add(Dropout(0.8))
    # model.add(Dense(16,activation='relu'))
    # # model.add(Dropout(0.8))
    # model.add(Dense(32,activation='relu'))
    # # model.add(Dropout(0.8))
    # model.add(Dense(16,activation='relu'))
    # # model.add(Dropout(0.8))
    # model.add(Dense(4,activation='relu'))
    model.add(Dense(1,activation='sigmoid'))
    return model
arch().summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 32)                96        
                                                                 
 dropout_4 (Dropout)         (None, 32)                0         
                                                                 
 dense_7 (Dense)             (None, 16)                528       
                                                                 
 dropout_5 (Dropout)         (None, 16)                0         
                                                                 
 dense_8 (Dense)             (None, 1)                 17        
                                                                 
Total params: 641 (2.50 KB)
Trainable params: 641 (2.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
def bceloss(y_true, y_pred):
    # Clip the prediction value to prevent log(0) error
    y_pred = K.clip(y_pred, K.epsilon(), 1 - K.epsilon())
    # Calculate the weighted binary cross entropy loss
    loss = -(0.1 * (y_true * K.log(y_pred)) + 0.9*((1 - y_true) * K.log(1 - y_pred)))
    return K.mean(loss, axis=-1)

model=arch()
model.summary
opt=SGD( learning_rate=0.01, momentum=0.9)
model.compile(loss=binary_crossentropy, optimizer='adam', metrics=['accuracy'])
model_path="../Model/NN2/{epoch:02d}-{val_accuracy:.4f}.h5"
checkpoint = ModelCheckpoint(model_path, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [19]:
H=model.fit(x_train,y_train,
          validation_data=(x_test, y_test),
          epochs=100,batch_size=64,
          callbacks=callbacks_list,
          verbose=1)

Epoch 1/100
 85/132 [==================>...........] - ETA: 0s - loss: 0.4990 - accuracy: 0.7632
Epoch 1: val_accuracy improved from -inf to 0.95611, saving model to ../Model/NN2/01-0.9561.h5
132/132 [==============================] - 1s 3ms/step - loss: 0.4307 - accuracy: 0.8065 - val_loss: 0.1808 - val_accuracy: 0.9561
Epoch 2/100
 99/132 [=====================>........] - ETA: 0s - loss: 0.2558 - accuracy: 0.9164
Epoch 2: val_accuracy improved from 0.95611 to 0.95833, saving model to ../Model/NN2/02-0.9583.h5
132/132 [==============================] - 0s 2ms/step - loss: 0.2465 - accuracy: 0.9212 - val_loss: 0.1671 - val_accuracy: 0.9583
Epoch 3/100
127/132 [===========================>..] - ETA: 0s - loss: 0.2221 - accuracy: 0.9361
Epoch 3: val_accuracy improved from 0.95833 to 0.96222, saving model to ../Model/NN2/03-0.9622.h5
132/132 [==============================] - 0s 2ms/step - loss: 0.2208 - accuracy: 0.9369 - val_loss: 0.1650 - val_accuracy: 0.9622
Epoch 4/100
132/132 [====

In [21]:
count=0
count1=0
y_pred=model.predict(x_test)
for i in range(y_pred.shape[0]):
    if y_test[i]==0:
        count+=1
        if y_pred[i]<0.5:
            count1+=1
print(count,count1)

113/113 [==============================] - 0s 780us/step
1833 1779


## GDA

In [20]:
import numpy as np
from scipy.stats import multivariate_normal

class GaussianDiscriminantAnalysis:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.class_priors = np.array([np.mean(y == c) for c in self.classes])

        self.means = []
        self.cov_matrices = []
        for c in self.classes:
            X_c = X[y == c]
            mean_c = np.mean(X_c, axis=0)
            cov_matrix_c = np.cov(X_c, rowvar=False)
            self.means.append(mean_c)
            self.cov_matrices.append(cov_matrix_c)

    def predict(self, X):
        posteriors = []

        for c in self.classes:
            class_prior = self.class_priors[int(c)]
            mean = self.means[int(c)]
            cov_matrix = self.cov_matrices[int(c)]
            mvn = multivariate_normal(mean=mean, cov=cov_matrix)
            posterior = class_prior * mvn.pdf(X)
            posteriors.append(posterior)

        posteriors = np.array(posteriors).T
        predicted_labels = np.argmax(posteriors, axis=1)

        return predicted_labels



# Initialize and train GDA
gda = GaussianDiscriminantAnalysis()
gda.fit(x_train, y_train)

# Make predictions
y_pred = gda.predict(x_train)
# Calculate accuracy
accuracy = np.mean(y_pred == y_train)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 96.15%


## RNN

In [48]:
min,max= -(2**16),(2**16)
print('Min: %.3f, Max: %.3f' % (x.min(), x.max()))
x= (x-min)/(max-min)
print('Min: %.3f, Max: %.3f' % (x.min(), x.max()))

Min: -32291.412, Max: 28569.142
Min: 0.254, Max: 0.718


In [49]:
st,ed=700,2700
x_train, x_test, y_train, y_test = train_test_split(x[:,st:ed,:], y, test_size=0.30, random_state=45)
x_train=x_train.reshape((x_train.shape[0],200,20))
x_test=x_test.reshape((x_test.shape[0],200,20))
print(x_train.shape)
print(y_train.sum())

(8400, 200, 20)
4233.0


In [61]:
def rnn():
    model=Sequential()
    model.add(Input(shape=(200,20)))
    model.add(layers.LSTM(units=16, return_sequences=True))
    model.add(layers.LSTM(units=8, return_sequences=True))
    model.add(layers.LSTM(units=4, return_sequences=False))
#     model.add(layers.Dense(4,activation='relu'))
    model.add(layers.Dense(1,activation='sigmoid'))
    return model

In [62]:
model=rnn()
model.summary()
opt=SGD( learning_rate=0.001, momentum=0.9)
model.compile(loss=binary_crossentropy, optimizer='adam', metrics=['accuracy'])
model_path="../Model/RNN_new/{epoch:02d}-{val_accuracy:.4f}.h5"
checkpoint = ModelCheckpoint(model_path, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_29 (LSTM)              (None, 200, 16)           2368      
                                                                 
 lstm_30 (LSTM)              (None, 200, 8)            800       
                                                                 
 lstm_31 (LSTM)              (None, 4)                 208       
                                                                 
 dense_11 (Dense)            (None, 1)                 5         
                                                                 
Total params: 3381 (13.21 KB)
Trainable params: 3381 (13.21 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [64]:
with tf.device("/gpu:0"):
    H=model.fit(x_train,y_train,
            validation_data=(x_test, y_test),
            epochs=200,batch_size=32,
            callbacks=callbacks_list,
            verbose=1)

Epoch 1/200


2023-10-12 14:58:39.275865: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:425] Loaded runtime CuDNN library: 8.3.2 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-10-12 14:58:39.276790: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at cudnn_rnn_ops.cc:1762 : UNKNOWN: Fail to find the dnn implementation.


UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential_11/lstm_29/PartitionedCall]] [Op:__inference_train_function_29808]